---
- name: Enable default Network
  ansible.builtin.command: "virsh net-autostart {{ default }}"
  args:
    # Todo: Figure out where it's Saved!
    creates: "{{ idempotent_file }}"
  notify: make Idempotent
  become: true	# Manjaro requires sudo for virsh commands
